/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller
import Math.pow
import scala.collection.parallel.CollectionConverters._

object App {
  def main(args: Array[String]): Unit = {
    println(greeting())

    val Riego = new Finca()
    val Bench = new Benchmark()

    //Probando funciones de la finca
    val f = Riego.FincaALAzar(10)
    val d = Riego.DistanciaAlAzar(10)
    val p = Riego.ProgramacionAlAlzar(10)
    println(f"\n{$f}")
    println(f"\n{$d}")
    println(f"\n{$p}")
    
  }


  

  def greeting(): String = "Hello, world!"
}
